# Generated by Django 2.2.6 on 2019-11-07 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BurndownChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_efforts', models.IntegerField()),
                ('remaining_efforts', models.IntegerField()),
                ('burndown_efforts', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PBI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('NS', 'Not started'), ('IP', 'In progress'), ('C', 'Complete')], default='IP', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SprintBacklog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('pbi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprints.PBI')),
            ],
        ),
        migrations.AddField(
            model_name='pbi',
            name='sprint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprints.SprintBacklog'),
        ),
    ]
