# Generated by Django 2.2.6 on 2019-12-07 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0002_auto_20191207_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pbi',
            name='priority',
            field=models.IntegerField(default=models.AutoField(primary_key=True, serialize=False)),
        ),
    ]
