# Generated by Django 2.2.6 on 2019-11-08 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0002_auto_20191108_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pbi',
            name='sprint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sprints.SprintBacklog'),
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('initialEstimatedEffort', models.IntegerField(null=True)),
                ('remaining_efforts', models.IntegerField(null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprints.Task')),
            ],
        ),
    ]
