# Generated by Django 2.2.6 on 2019-12-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0003_auto_20191207_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pbi',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
