# Generated by Django 2.2.6 on 2019-12-07 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0004_auto_20191207_0723'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pbi',
            options={'ordering': ['priority']},
        ),
    ]
