# Generated by Django 2.2.6 on 2019-11-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0004_developer_project_scrummaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='Developers',
            field=models.ManyToManyField(null=True, to='sprints.Developer'),
        ),
    ]
