# Generated by Django 2.2.6 on 2019-11-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0008_auto_20191108_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprintbacklog',
            name='averageEf',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='sprintbacklog',
            name='remainEf',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='sprintbacklog',
            name='totalEf',
            field=models.IntegerField(default=10),
        ),
    ]
