# Generated by Django 2.2.6 on 2019-11-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0009_auto_20191108_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprintbacklog',
            name='initialEf',
            field=models.IntegerField(default=10),
        ),
    ]
