# Generated by Django 2.2.6 on 2019-11-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0010_sprintbacklog_initialef'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='remainEf',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='task',
            name='totalEf',
            field=models.IntegerField(default=10),
        ),
    ]
