# Generated by Django 2.2.6 on 2019-11-15 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0011_auto_20191108_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sprints.Project'),
        ),
    ]
