# Generated by Django 2.2.6 on 2019-11-24 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0013_auto_20191124_0233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.RemoveField(
            model_name='task',
            name='remainEf',
        ),
        migrations.RemoveField(
            model_name='task',
            name='totalEf',
        ),
    ]
