# Generated by Django 2.2.6 on 2019-11-24 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0014_auto_20191124_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sprintNumber',
            field=models.IntegerField(default=0),
        ),
    ]
