# Generated by Django 2.2.6 on 2019-11-24 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0015_project_sprintnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='pbi',
            name='remainStory',
            field=models.IntegerField(default=10, null=True),
        ),
    ]
