# Generated by Django 2.2.6 on 2019-11-24 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0016_pbi_remainstory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pbi',
            name='status',
            field=models.CharField(choices=[('NS', 'Not started'), ('IP', 'In progress'), ('C', 'Complete'), ('NF', 'NotFinish')], default='NS', max_length=10),
        ),
    ]
